package sql1cv8

// Типы полей (имена)
var types map[string]string
var typesLang = map[string]map[string]string{
	"en": {},
	"ru": {
		"NULL": "Тип.NULL",
		"0x01": "Тип.Неопределено",
		"0x02": "Тип.Булево",
		"0x03": "Тип.Число",
		"0x04": "Тип.Дата",
		"0x05": "Тип.Строка",
		"0x06": "Тип.Двоичный",
		"0x08": "Тип.Ссылка",
	},
}

// Стандартные поля (имена)
var fields map[string]string
var fieldsLang = map[string]map[string]string{
	"en": {},
	"ru": {
		"_Active":          "Активность",
		"_BusinessProcess": "БизнесПроцесс",
		"_Code":            "Код",
		"_Completed":       "Завершен",
		"_Date_Time":       "Дата",
		"_Description":     "Наименование",
		"_DimHash":         "ХэшИзмерений",
		"_EnumOrder":       "Порядок",
		"_Executed":        "Выполнена",
		"_Folder":          "Группа",
		"_HeadTaskRRef":    "ВедущаяЗадача",
		"_IDRRef":          "Ссылка",
		"_IDTRef":          "ВидСсылки",
		"_KeyField":        "КлючЗаписи",
		"_LineNo":          "НомерСтроки",
		"_Marked":          "ПометкаУдаления",
		"_Name":            "Наименование",
		"_Number":          "Номер",
		"_NumberPrefix":    "Префикс",
		"_OwnerID":         "Владелец",
		"_ParentIDRRef":    "Родитель",
		"_Period":          "Период",
		"_Point":           "ТочкаМаршрута",
		"_Posted":          "Проведен",
		"_PredefinedID":    "Предопределенное",
		"_RecorderRRef":    "Регистратор",
		"_RecorderTRef":    "ВидРегистратора",
		"_RecordKey":       "КлючЗаписи",
		"_RecordKind":      "ВидДвижения",
		"_RoutePointOrder": "Порядок",
		"_Splitter":        "Разделитель",
		"_Started":         "Стартован",
		"_Type":            "ТипЗначения",
		"_Version":         "Версия",
	},
}

// Стандартные поля (синонимы)
var fieldSynonyms = map[string]map[string]string{
	"_Active":          {"ru": "Активность"},
	"_BusinessProcess": {"ru": "Бизнес-процесс"},
	"_Code":            {"ru": "Код"},
	"_Completed":       {"ru": "Завершен"},
	"_Date_Time":       {"ru": "Дата"},
	"_Description":     {"ru": "Наименование"},
	"_DimHash":         {"ru": "Хэш измерений"},
	"_EnumOrder":       {"ru": "Порядок"},
	"_Executed":        {"ru": "Выполнена"},
	"_Folder":          {"ru": "Группа"},
	"_HeadTaskRRef":    {"ru": "Ведущая задача"},
	"_IDRRef":          {"ru": "Ссылка"},
	"_IDTRef":          {"ru": "Вид ссылки"},
	"_KeyField":        {"ru": "Ключ записи"},
	"_LineNo":          {"ru": "Номер строки"},
	"_Marked":          {"ru": "Пометка удаления"},
	"_Name":            {"ru": "Наименование"},
	"_Number":          {"ru": "Номер"},
	"_NumberPrefix":    {"ru": "Префикс"},
	"_OwnerID":         {"ru": "Владелец"},
	"_ParentIDRRef":    {"ru": "Родитель"},
	"_Period":          {"ru": "Период"},
	"_Point":           {"ru": "Точка маршрута"},
	"_Posted":          {"ru": "Проведен"},
	"_PredefinedID":    {"ru": "Предопределенное"},
	"_RecorderRRef":    {"ru": "Регистратор"},
	"_RecorderTRef":    {"ru": "Вид регистратора"},
	"_RecordKey":       {"ru": "Ключ записи"},
	"_RecordKind":      {"ru": "Вид движения"},
	"_RoutePointOrder": {"ru": "Порядок"},
	"_Splitter":        {"ru": "Разделитель"},
	"_Started":         {"ru": "Стартован"},
	"_Type":            {"ru": "Тип значения"},
	"_Version":         {"ru": "Версия"},
}
