package sql1cv8

// Типы полей
var types = map[string]string{
	"Тип.NULL":         "NULL",
	"Тип.Неопределено": "0x01",
	"Тип.Булево":       "0x02",
	"Тип.Число":        "0x03",
	"Тип.Дата":         "0x04",
	"Тип.Строка":       "0x05",
	"Тип.Двоичный":     "0x06",
	"Тип.Ссылка":       "0x08",
}

// Стандартные поля
var fields = map[string]string{
	"_Active":          "Активность",
	"_BusinessProcess": "БизнесПроцесс",
	"_Code":            "Код",
	"_Completed":       "Завершен",
	"_Date_Time":       "Дата",
	"_Description":     "Наименование",
	"_DimHash":         "ХэшИзмерений",
	"_EnumOrder":       "Порядок",
	"_Executed":        "Выполнена",
	"_Folder":          "Группа",
	"_HeadTaskRRef":    "ВедущаяЗадача",
	"_IDRRef":          "Ссылка",
	"_KeyField":        "КлючЗаписи",
	"_LineNo":          "НомерСтроки",
	"_Marked":          "ПометкаУдаления",
	"_Name":            "Наименование",
	"_Number":          "Номер",
	"_NumberPrefix":    "Префикс",
	"_OwnerID":         "Владелец",
	"_ParentIDRRef":    "Родитель",
	"_Period":          "Период",
	"_Point":           "ТочкаМаршрута",
	"_Posted":          "Проведен",
	"_PredefinedID":    "Предопределенное",
	"_RecorderRRef":    "Регистратор",
	"_RecorderTRef":    "ВидРегистратора",
	"_RecordKey":       "КлючЗаписи",
	"_RecordKind":      "ВидДвижения",
	"_RoutePointOrder": "Порядок",
	"_Splitter":        "Разделитель",
	"_Started":         "Стартован",
	"_Type":            "ТипЗначения",
	"_Version":         "Версия",
}
