package sql1cv8

// Типы полей (имена)
var types = map[string]map[string]string{
	"en": {},
	"ru": {
		"NULL": "Тип.NULL",
		"0x01": "Тип.Неопределено",
		"0x02": "Тип.Булево",
		"0x03": "Тип.Число",
		"0x04": "Тип.Дата",
		"0x05": "Тип.Строка",
		"0x06": "Тип.Двоичный",
		"0x08": "Тип.Ссылка",
	},
}

// Стандартные поля (имена)
var fields = map[string]map[string]string{
	"en": {},
	"ru": {
		"_":                   "",
		"_AccountCtRRef":      "СчетКт",
		"_AccountDtRRef":      "СчетДт",
		"_AccountRRef":        "Счет",
		"_Active":             "Активность",
		"_BaseAsAct":          "ПериодДействияБазовый",
		"_BaseCKBaseCK":       "ВидРасчета",
		"_BusinessProcess":    "БизнесПроцесс",
		"_Code":               "Код",
		"_Completed":          "Завершен",
		"_Correspond":         "ВидДвижения",
		"_Date_Time":          "Дата",
		"_Description":        "Наименование",
		"_DimHash":            "ХэшИзмерений",
		"_DimIsMetadata":      "Предопределенное",
		"_DimKindRRef":        "ВидСубконто",
		"_DisplacedCKDisplCK": "ВидРасчета",
		"_DocumentRRef":       "Документ",
		"_DocumentTRef":       "ВидДокумента",
		"_EDHash":             "ХэшПроводки",
		"_EDHashCt":           "ХэшПроводкиКт",
		"_EDHashDt":           "ХэшПроводкиДт",
		"_EnumOrder":          "Порядок",
		"_Executed":           "Выполнена",
		"_Folder":             "ЭтоГруппа",
		"_HeadTaskRRef":       "ВедущаяЗадача",
		"_IDRRef":             "Ссылка",
		"_IDTRef":             "ВидСсылки",
		"_KeyField":           "КлючЗаписи",
		"_Kind":               "Вид",
		"_KindAt":             "ВидСубконто",
		"_KindCt":             "ВидСубконтоКт",
		"_KindDt":             "ВидСубконтоДт",
		"_KindRRef":           "Вид",
		"_KindSubconto":       "ВидСубконто",
		"_KindSubcontoCt":     "ВидСубконтоКт",
		"_KindSubcontoDt":     "ВидСубконтоДт",
		"_LeadingCKLeadingCK": "ВидРасчета",
		"_LineNo":             "НомерСтроки",
		"_Marked":             "ПометкаУдаления",
		"_Name":               "Наименование",
		"_Number":             "Номер",
		"_NumberPrefix":       "Префикс",
		"_OffBalance":         "Забалансовый",
		"_OrderField":         "Порядок",
		"_OwnerID":            "Владелец",
		"_ParentIDRRef":       "Родитель",
		"_Period":             "Период",
		"_PeriodAdjustment":   "УточнениеПериода",
		"_Point":              "ТочкаМаршрута",
		"_Posted":             "Проведен",
		"_PredefinedID":       "Предопределенное",
		"_ReceivedNo":         "НомерПринятого",
		"_RecorderRRef":       "Регистратор",
		"_RecorderTRef":       "ВидРегистратора",
		"_RecordKey":          "КлючЗаписи",
		"_RecordKind":         "ВидДвижения",
		"_RoutePointOrder":    "Порядок",
		"_SentNo":             "НомерОтправленного",
		"_Splitter":           "Разделитель",
		"_Started":            "Стартован",
		"_TurnoverOnly":       "ТолькоОбороты",
		"_Type":               "ТипЗначения",
		"_Value":              "Значение",
		"_ValueAt":            "Субконто",
		"_ValueCt":            "СубконтоКт",
		"_ValueDt":            "СубконтоДт",
		"_ValueSubconto":      "Субконто",
		"_ValueSubcontoCt":    "СубконтоКт",
		"_ValueSubcontoDt":    "СубконтоДт",
		"_Version":            "Версия",
	},
}

// Стандартные поля (синонимы)
var fieldSynonyms = map[string]map[string]string{
	"_":                   {"ru": ""},
	"_AccountCtRRef":      {"ru": "Счет по кредиту"},
	"_AccountDtRRef":      {"ru": "Счет по дебету"},
	"_AccountRRef":        {"ru": "Счет"},
	"_Active":             {"ru": "Активность"},
	"_BaseAsAct":          {"ru": "Использует период действия"},
	"_BaseCKBaseCK":       {"ru": "ВидРасчета"},
	"_BusinessProcess":    {"ru": "Бизнес-процесс"},
	"_Code":               {"ru": "Код"},
	"_Completed":          {"ru": "Завершен"},
	"_Correspond":         {"ru": "ВидДвижения"},
	"_Date_Time":          {"ru": "Дата"},
	"_Description":        {"ru": "Наименование"},
	"_DimHash":            {"ru": "Хэш измерений"},
	"_DimIsMetadata":      {"ru": "Предопределенное"},
	"_DimKindRRef":        {"ru": "Вид субконто"},
	"_DisplacedCKDisplCK": {"ru": "ВидРасчета"},
	"_DocumentRRef":       {"ru": "Документ"},
	"_DocumentTRef":       {"ru": "Вид документа"},
	"_EDHash":             {"ru": "Хэш проводки"},
	"_EDHashCt":           {"ru": "Хэш проводки по кредиту"},
	"_EDHashDt":           {"ru": "Хэш проводки по дебету"},
	"_EnumOrder":          {"ru": "Порядок"},
	"_Executed":           {"ru": "Выполнена"},
	"_Folder":             {"ru": "Это группа"},
	"_HeadTaskRRef":       {"ru": "Ведущая задача"},
	"_IDRRef":             {"ru": "Ссылка"},
	"_IDTRef":             {"ru": "Вид ссылки"},
	"_KeyField":           {"ru": "Ключ записи"},
	"_Kind":               {"ru": "Вид"},
	"_KindAt":             {"ru": "Вид субконто"},
	"_KindCt":             {"ru": "Вид субконто по кредиту"},
	"_KindDt":             {"ru": "Вид субконто по дебету"},
	"_KindRRef":           {"ru": "Вид"},
	"_KindSubconto":       {"ru": "Вид субконто"},
	"_KindSubcontoCt":     {"ru": "Вид субконто по кредиту"},
	"_KindSubcontoDt":     {"ru": "Вид субконто по дебету"},
	"_LeadingCKLeadingCK": {"ru": "ВидРасчета"},
	"_LineNo":             {"ru": "Номер строки"},
	"_Marked":             {"ru": "Пометка удаления"},
	"_Name":               {"ru": "Наименование"},
	"_Number":             {"ru": "Номер"},
	"_NumberPrefix":       {"ru": "Префикс"},
	"_OffBalance":         {"ru": "Забалансовый"},
	"_OrderField":         {"ru": "Порядок"},
	"_OwnerID":            {"ru": "Владелец"},
	"_ParentIDRRef":       {"ru": "Родитель"},
	"_Period":             {"ru": "Период"},
	"_PeriodAdjustment":   {"ru": "Уточнение периода"},
	"_Point":              {"ru": "Точка маршрута"},
	"_Posted":             {"ru": "Проведен"},
	"_PredefinedID":       {"ru": "Предопределенное"},
	"_ReceivedNo":         {"ru": "Номер принятого"},
	"_RecorderRRef":       {"ru": "Регистратор"},
	"_RecorderTRef":       {"ru": "Вид регистратора"},
	"_RecordKey":          {"ru": "Ключ записи"},
	"_RecordKind":         {"ru": "Вид движения"},
	"_RoutePointOrder":    {"ru": "Порядок"},
	"_SentNo":             {"ru": "Номер отправленного"},
	"_Splitter":           {"ru": "Разделитель"},
	"_Started":            {"ru": "Стартован"},
	"_TurnoverOnly":       {"ru": "Только обороты"},
	"_Type":               {"ru": "Тип значения"},
	"_Value":              {"ru": "Значение"},
	"_ValueAt":            {"ru": "Субконто"},
	"_ValueCt":            {"ru": "Субконто по кредиту"},
	"_ValueDt":            {"ru": "Субконто по дебету"},
	"_ValueSubconto":      {"ru": "Субконто"},
	"_ValueSubcontoCt":    {"ru": "Субконто по кредиту"},
	"_ValueSubcontoDt":    {"ru": "Субконто по дебету"},
	"_Version":            {"ru": "Версия"},
}
