name: test module

on: create

jobs:

  test:
    runs-on: ubuntu-20.04

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "kaiNah1roCeech&o"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: setup mssql-tools
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install mssql-tools

    - name: create database
      run: /opt/mssql-tools/bin/sqlcmd -U sa -P Bu,Quiexie4aenee -H localhost -d master -l 5 -t 30 -i ./database_test.sql

    - name: test
      run: go test -v ./...
